version: 2

dockerused: &dockerused
  docker: 
    - image: circleci/node:10.13.0-stretch #host(for unofficial dokcer)/image:tag(version)
  working_directory: ~/workspace/code #optional

jobs:
  build:
    <<: *dockerused
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - code
  test:
    <<: *dockerused
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Testing
          command: yarn test:unit

workflows:  
  version: 2
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build