version: 2

jobs:
  build:
    docker:
      - image: circleci/node:10.13.0-stretch #host(for unofficial dokcer)/image:tag(version)
    working_directory: ~/workspace/code #optional
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install
      - run:
          name: Build
          command: yarn build
